//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/PersonaService.Data")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePersona {
            get {
                return this.ApePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePersonaField, value) != true)) {
                    this.ApePersonaField = value;
                    this.RaisePropertyChanged("ApePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocPersona {
            get {
                return this.DocPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocPersonaField, value) != true)) {
                    this.DocPersonaField = value;
                    this.RaisePropertyChanged("DocPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPersona {
            get {
                return this.NomPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPersonaField, value) != true)) {
                    this.NomPersonaField = value;
                    this.RaisePropertyChanged("NomPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IPersonaService")]
    public interface IPersonaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/listarPersonas", ReplyAction="http://tempuri.org/IPersonaService/listarPersonasResponse")]
        System.Collections.Generic.List<Cliente.DataService.Persona> listarPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/listarPersonas", ReplyAction="http://tempuri.org/IPersonaService/listarPersonasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente.DataService.Persona>> listarPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/traePersona", ReplyAction="http://tempuri.org/IPersonaService/traePersonaResponse")]
        Cliente.DataService.Persona traePersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/traePersona", ReplyAction="http://tempuri.org/IPersonaService/traePersonaResponse")]
        System.Threading.Tasks.Task<Cliente.DataService.Persona> traePersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/nuevaPersona", ReplyAction="http://tempuri.org/IPersonaService/nuevaPersonaResponse")]
        bool nuevaPersona(Cliente.DataService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/nuevaPersona", ReplyAction="http://tempuri.org/IPersonaService/nuevaPersonaResponse")]
        System.Threading.Tasks.Task<bool> nuevaPersonaAsync(Cliente.DataService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/editaPersona", ReplyAction="http://tempuri.org/IPersonaService/editaPersonaResponse")]
        bool editaPersona(Cliente.DataService.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/editaPersona", ReplyAction="http://tempuri.org/IPersonaService/editaPersonaResponse")]
        System.Threading.Tasks.Task<bool> editaPersonaAsync(Cliente.DataService.Persona persona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonaServiceChannel : Cliente.DataService.IPersonaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaServiceClient : System.ServiceModel.ClientBase<Cliente.DataService.IPersonaService>, Cliente.DataService.IPersonaService {
        
        public PersonaServiceClient() {
        }
        
        public PersonaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Cliente.DataService.Persona> listarPersonas() {
            return base.Channel.listarPersonas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente.DataService.Persona>> listarPersonasAsync() {
            return base.Channel.listarPersonasAsync();
        }
        
        public Cliente.DataService.Persona traePersona(int id) {
            return base.Channel.traePersona(id);
        }
        
        public System.Threading.Tasks.Task<Cliente.DataService.Persona> traePersonaAsync(int id) {
            return base.Channel.traePersonaAsync(id);
        }
        
        public bool nuevaPersona(Cliente.DataService.Persona persona) {
            return base.Channel.nuevaPersona(persona);
        }
        
        public System.Threading.Tasks.Task<bool> nuevaPersonaAsync(Cliente.DataService.Persona persona) {
            return base.Channel.nuevaPersonaAsync(persona);
        }
        
        public bool editaPersona(Cliente.DataService.Persona persona) {
            return base.Channel.editaPersona(persona);
        }
        
        public System.Threading.Tasks.Task<bool> editaPersonaAsync(Cliente.DataService.Persona persona) {
            return base.Channel.editaPersonaAsync(persona);
        }
    }
}
