//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwWCF.WCFPersonaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WcfPersona.Model")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePersona {
            get {
                return this.ApePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePersonaField, value) != true)) {
                    this.ApePersonaField = value;
                    this.RaisePropertyChanged("ApePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocPersona {
            get {
                return this.DocPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocPersonaField, value) != true)) {
                    this.DocPersonaField = value;
                    this.RaisePropertyChanged("DocPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPersona {
            get {
                return this.NomPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPersonaField, value) != true)) {
                    this.NomPersonaField = value;
                    this.RaisePropertyChanged("NomPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPersonaReference.IPersonaData")]
    public interface IPersonaData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaData/listar", ReplyAction="http://tempuri.org/IPersonaData/listarResponse")]
        System.Collections.Generic.List<MVCwWCF.WCFPersonaReference.Persona> listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaData/traePersona", ReplyAction="http://tempuri.org/IPersonaData/traePersonaResponse")]
        MVCwWCF.WCFPersonaReference.Persona traePersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaData/creaPersona", ReplyAction="http://tempuri.org/IPersonaData/creaPersonaResponse")]
        bool creaPersona(MVCwWCF.WCFPersonaReference.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaData/editaPersona", ReplyAction="http://tempuri.org/IPersonaData/editaPersonaResponse")]
        bool editaPersona(MVCwWCF.WCFPersonaReference.Persona persona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonaDataChannel : MVCwWCF.WCFPersonaReference.IPersonaData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaDataClient : System.ServiceModel.ClientBase<MVCwWCF.WCFPersonaReference.IPersonaData>, MVCwWCF.WCFPersonaReference.IPersonaData {
        
        public PersonaDataClient() {
        }
        
        public PersonaDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MVCwWCF.WCFPersonaReference.Persona> listar() {
            return base.Channel.listar();
        }
        
        public MVCwWCF.WCFPersonaReference.Persona traePersona(int id) {
            return base.Channel.traePersona(id);
        }
        
        public bool creaPersona(MVCwWCF.WCFPersonaReference.Persona persona) {
            return base.Channel.creaPersona(persona);
        }
        
        public bool editaPersona(MVCwWCF.WCFPersonaReference.Persona persona) {
            return base.Channel.editaPersona(persona);
        }
    }
}
