//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonaService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int IdPersona { get; set; }
        public string DocPersona { get; set; }
        public string NomPersona { get; set; }
        public string ApePersona { get; set; }
        public int Edad { get; set; }
    }
}
